### PR TITLE
CLI

### PR DESCRIPTION
**Pull request by amartin96**
You can now specify a number of times to run all algorithms, or an algorithm to run once (like in P2).  We haven't done anything regarding averaging hit ratios for the report.

### CODE REVIEW

**Comment by amartin96** [comment]
I just realized that the multiple run functionality doesn't do what it should.  It needs to use the same set of generated processes for each algorithm within a run.  I can fix that I think.

**Comment by RyanLoringCooper** [comment]
Sounds great. Could you also print the banners between runs on stderr also? I think we should print the average data per run on stderr so that it is easy to log to a file.

**Comment by amartin96** [comment]
Ah... actually, I'm not sure how to go about fixing this.  The generateProcesses function takes a pointer to the PageTable object.  Why is that?

**Comment by RyanLoringCooper** [comment]
It is because each process needs a reference to the PageTable so that they can reference pages in it. You could copy procs, which is the second argument to runAlg and use the copy of procs for an individual run.

**Comment by RyanLoringCooper** [comment]
What if you have makeRun return a copy of procs before the algorithm was run?

**Comment by amartin96** [comment]
I don't see how that would work.  Procs is returned by generateProcesses, and all the Process objects therein would be bound to the corresponding PageTable.  If I were to hand that same procs pointer with a different PageTable object to another runAlg, wouldn't it use the wrong page table?

**Comment by amartin96** [comment]
Does there need to be a method in Process to reassign the PageTable?

**Comment by RyanLoringCooper** [comment]
Hold on, I'll make a pull request to this branch in a moment.

**Comment by amartin96** [comment]
Not sure what "out of memory, 0" is, but it also prints to stderr.  Anyway, done.

**Comment by RyanLoringCooper** [comment]
Oh yeah. Whoopse. That was from earlier testing.

**Pull request merged**
