### PR TITLE
Fifo

### PR DESCRIPTION
**Pull request by cindykdao**
Not done yet. Been thinking about whether or not this is the best way to go about it but it was compiling before and now it isn't, I think...? >:(

--Added global variable **reqNum** as a counter for unique page table entries, which are pages that haven't been referenced before (should keep track of the FIRST time each page is referenced)
--Added int **requestNum** into PageTableEntry, sets itself equal to reqNum when entry is unique
--If page has been referenced before, requestNum is equal to the page's initial requestNum, which is found by matching the ownerPage/pageNum
--FIFO replaces page with lowest requestNum

I must be doing this wrong and/or overcomplicating things... T^T

Edit: Also should probably steer clear of making new global variables but the fact that this compiled before makes me suspicious, unless I was imagining it.

### CODE REVIEW

**Comment by amartin96** [comment]
I think a good approach to FIFO would be to add a field to struct PageTableEntry that stores the time the page was first placed in memory.  The replacement algorithm could then search the table for the page with the earliest arrival time and replace it.

**Comment by amartin96** [comment]
What's the status on this?

**Review by RyanLoringCooper — APPROVED** [review]
It works

**Comment by cindykdao** [comment]
Thanks for checking!

**Pull request merged**
